language: python
python:
  - "2.7"
services:
  - docker
install:
  - make  deps
script:
  - make  test
  - make  test_cov
  - make  test_xunit
after_success:
  - make  docker_build
  - PASSWORD=$DOCKER_PASSWORD make  docker_push
